- hosts: all
  connection: local
  tasks:
    - set_fact:
        datasource_post_data: >-
          {"name": "Graphite",
          "type": "graphite",
          "url": "http://localhost:8888",
          "access": "proxy",
          "basicAuth": false}

    # See: http://docs.grafana.org/http_api/data_source/
    - name: Create the Grafana datasource
      command: >-
        curl -u admin:admin
             -H 'Content-Type: application/json'
             -X POST
             -d '{{ datasource_post_data }}'
             http://127.0.0.1:3000/api/datasources
